# Generated by Django 5.0 on 2025-07-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('price1', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('price2', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('price3', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
            ],
        ),
    ]
