# Generated by Django 5.0 on 2025-07-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactemail_subscribtionemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactemail',
            old_name='message',
            new_name='msg',
        ),
    ]
