# Generated by Django 5.0 on 2025-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_price1_alter_service_price2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
