# Generated by Django 5.0 on 2025-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_price1_alter_service_price2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='body',
        ),
        migrations.AddField(
            model_name='service',
            name='cover_img',
            field=models.ImageField(default='image', upload_to='img/post_cover'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Write Something'),
        ),
        migrations.AddField(
            model_name='service',
            name='img1',
            field=models.ImageField(default='img/post_cover/image_1.jpg', upload_to='img/img'),
        ),
        migrations.AddField(
            model_name='service',
            name='img2',
            field=models.ImageField(default='img/post_cover/image_1.jpg', upload_to='img/img'),
        ),
        migrations.AddField(
            model_name='service',
            name='img3',
            field=models.ImageField(default='img/post_cover/image_1.jpg', upload_to='img/img'),
        ),
        migrations.AddField(
            model_name='service',
            name='img4',
            field=models.ImageField(default='img/post_cover/image_1.jpg', upload_to='img/img'),
        ),
    ]
