# Generated by Django 5.0 on 2025-07-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_message_contactemail_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactemail',
            old_name='email',
            new_name='memail',
        ),
    ]
