# Generated by Django 5.0 on 2025-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_body_service_cover_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
