# Generated by Django 5.0 on 2025-07-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_email_contactemail_memail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribtionEmail',
        ),
    ]
