# Generated by Django 5.0 on 2025-08-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_subscribtionemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover_img', models.ImageField(upload_to='img/post_cover')),
                ('link', models.CharField(max_length=100)),
                ('work', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='core.service')),
            ],
        ),
    ]
