# Generated by Django 5.0 on 2025-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
