# Generated by Django 5.0 on 2025-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='https://cdn-icons-png.flaticon.com/512/847/847969.png', upload_to='img/profile_images'),
        ),
    ]
