# Generated by Django 5.0 on 2025-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, default='Default Image', upload_to='img/post_cover'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'PUBLISHED'), ('draft', 'DRAFT')], default='draft', max_length=10),
        ),
    ]
