# Generated by Django 5.0 on 2025-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_img_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, default='img/blog-1.jpg', upload_to='img/post_cover'),
        ),
    ]
