# Generated by Django 5.0 on 2025-07-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'PUBLISHED'), ('draft', 'DRAFT')], default='published', max_length=10),
        ),
    ]
